namespace yMoi.Constants
{
    public class Contants
    {
        public const int SUCCESS = 1;
        public const int ERROR = 0;
        public const int SUCCESS_CODE = 200;
        public const string MESSAGE_SUCCESS = "Thành công";

        public static readonly List<LanguageModel> languages = new List<LanguageModel>
        {
            new LanguageModel { Code = "vi", Name = "Tiếng Việt" },
            new LanguageModel { Code = "en", Name = "Tiếng Anh" },
            new LanguageModel { Code = "zh", Name = "Tiếng Trung" },
            new LanguageModel { Code = "ja", Name = "Tiếng Nhật" },
            new LanguageModel { Code = "ko", Name = "Tiếng Hàn" },
            new LanguageModel { Code = "fr", Name = "Tiếng Pháp" },
            new LanguageModel { Code = "de", Name = "Tiếng Đức" },
            new LanguageModel { Code = "es", Name = "Tiếng Tây Ban Nha" },
            new LanguageModel { Code = "pt", Name = "Tiếng Bồ Đào Nha" },
            new LanguageModel { Code = "it", Name = "Tiếng Ý" },
            new LanguageModel { Code = "ru", Name = "Tiếng Nga" },
            new LanguageModel { Code = "th", Name = "Tiếng Thái" },
            new LanguageModel { Code = "id", Name = "Tiếng Indonesia" },
            new LanguageModel { Code = "ms", Name = "Tiếng Malaysia" },
            new LanguageModel { Code = "hi", Name = "Tiếng Hindi" },
            new LanguageModel { Code = "ar", Name = "Tiếng Ả Rập" },
            new LanguageModel { Code = "tr", Name = "Tiếng Thổ Nhĩ Kỳ" },
            new LanguageModel { Code = "nl", Name = "Tiếng Hà Lan" },
            new LanguageModel { Code = "pl", Name = "Tiếng Ba Lan" },
            new LanguageModel { Code = "sv", Name = "Tiếng Thụy Điển" },
            new LanguageModel { Code = "no", Name = "Tiếng Na Uy" },
            new LanguageModel { Code = "da", Name = "Tiếng Đan Mạch" },
            new LanguageModel { Code = "fi", Name = "Tiếng Phần Lan" },
            new LanguageModel { Code = "cs", Name = "Tiếng Séc" },
            new LanguageModel { Code = "hu", Name = "Tiếng Hungary" },
            new LanguageModel { Code = "ro", Name = "Tiếng Romania" },
            new LanguageModel { Code = "el", Name = "Tiếng Hy Lạp" },
            new LanguageModel { Code = "uk", Name = "Tiếng Ukraina" },
            new LanguageModel { Code = "bg", Name = "Tiếng Bulgaria" },
            new LanguageModel { Code = "he", Name = "Tiếng Do Thái" },
            new LanguageModel { Code = "fa", Name = "Tiếng Ba Tư" },
            new LanguageModel { Code = "sr", Name = "Tiếng Serbia" },
            new LanguageModel { Code = "hr", Name = "Tiếng Croatia" },
            new LanguageModel { Code = "sk", Name = "Tiếng Slovakia" },
            new LanguageModel { Code = "sl", Name = "Tiếng Slovenia" },
            new LanguageModel { Code = "et", Name = "Tiếng Estonia" },
            new LanguageModel { Code = "lv", Name = "Tiếng Latvia" },
            new LanguageModel { Code = "lt", Name = "Tiếng Litva" },
            new LanguageModel { Code = "bn", Name = "Tiếng Bengal" },
            new LanguageModel { Code = "ta", Name = "Tiếng Tamil" },
            new LanguageModel { Code = "ur", Name = "Tiếng Urdu" },
            new LanguageModel { Code = "sw", Name = "Tiếng Swahili" },
            new LanguageModel { Code = "zu", Name = "Tiếng Zulu" },
            new LanguageModel { Code = "af", Name = "Tiếng Afrikaans" },
            new LanguageModel { Code = "ga", Name = "Tiếng Ireland" },
            new LanguageModel { Code = "is", Name = "Tiếng Iceland" },
            new LanguageModel { Code = "mn", Name = "Tiếng Mông Cổ" },
            new LanguageModel { Code = "km", Name = "Tiếng Khmer (Campuchia)" },
            new LanguageModel { Code = "lo", Name = "Tiếng Lào" },
            new LanguageModel { Code = "my", Name = "Tiếng Myanmar (Miến Điện)" },
            new LanguageModel { Code = "ne", Name = "Tiếng Nepal" },
            new LanguageModel { Code = "pa", Name = "Tiếng Punjab" },
            new LanguageModel { Code = "si", Name = "Tiếng Sinhala" },
            new LanguageModel { Code = "te", Name = "Tiếng Telugu" },
            new LanguageModel { Code = "ml", Name = "Tiếng Malayalam" },
            new LanguageModel { Code = "kk", Name = "Tiếng Kazakhstan" },
            new LanguageModel { Code = "uz", Name = "Tiếng Uzbek" },
            new LanguageModel { Code = "tk", Name = "Tiếng Turkmen" },
            new LanguageModel { Code = "ky", Name = "Tiếng Kyrgyz" },
            new LanguageModel { Code = "tg", Name = "Tiếng Tajik" },
            new LanguageModel { Code = "ps", Name = "Tiếng Pashto" },
            new LanguageModel { Code = "bo", Name = "Tiếng Tây Tạng" },
            new LanguageModel { Code = "am", Name = "Tiếng Amharic" },
            new LanguageModel { Code = "ha", Name = "Tiếng Hausa" },
            new LanguageModel { Code = "yo", Name = "Tiếng Yoruba" },
            new LanguageModel { Code = "xh", Name = "Tiếng Xhosa" },
            new LanguageModel { Code = "st", Name = "Tiếng Sesotho" },
            new LanguageModel { Code = "sn", Name = "Tiếng Shona" },
            new LanguageModel { Code = "mg", Name = "Tiếng Malagasy" },
            new LanguageModel { Code = "rw", Name = "Tiếng Kinyarwanda" },
            new LanguageModel { Code = "so", Name = "Tiếng Somali" },
            new LanguageModel { Code = "ny", Name = "Tiếng Nyanja (Chichewa)" },
            new LanguageModel { Code = "su", Name = "Tiếng Sunda" },
            new LanguageModel { Code = "jv", Name = "Tiếng Java" },
            new LanguageModel { Code = "la", Name = "Tiếng Latinh" },
            new LanguageModel { Code = "eu", Name = "Tiếng Basque" },
            new LanguageModel { Code = "gl", Name = "Tiếng Galicia" },
            new LanguageModel { Code = "mt", Name = "Tiếng Malta" },
            new LanguageModel { Code = "sq", Name = "Tiếng Albania" },
            new LanguageModel { Code = "bs", Name = "Tiếng Bosnia" },
            new LanguageModel { Code = "mk", Name = "Tiếng Macedonia" },
            new LanguageModel { Code = "ca", Name = "Tiếng Catalan" },
            new LanguageModel { Code = "cy", Name = "Tiếng Wales" },
            new LanguageModel { Code = "gd", Name = "Tiếng Gael Scotland" }
        };


        public static readonly List<Nationality> nationalities = new List<Nationality>
        {
            new() { Code = "AF", Name = "Afghanistan" },
            new() { Code = "AL", Name = "Albania" },
            new() { Code = "DZ", Name = "Algeria" },
            new() { Code = "AD", Name = "Andorra" },
            new() { Code = "AO", Name = "Angola" },
            new() { Code = "AG", Name = "Antigua và Barbuda" },
            new() { Code = "AR", Name = "Argentina" },
            new() { Code = "AM", Name = "Armenia" },
            new() { Code = "AU", Name = "Úc" },
            new() { Code = "AT", Name = "Áo" },
            new() { Code = "AZ", Name = "Azerbaijan" },
            new() { Code = "BS", Name = "Bahamas" },
            new() { Code = "BH", Name = "Bahrain" },
            new() { Code = "BD", Name = "Bangladesh" },
            new() { Code = "BB", Name = "Barbados" },
            new() { Code = "BY", Name = "Belarus" },
            new() { Code = "BE", Name = "Bỉ" },
            new() { Code = "BZ", Name = "Belize" },
            new() { Code = "BJ", Name = "Benin" },
            new() { Code = "BT", Name = "Bhutan" },
            new() { Code = "BO", Name = "Bolivia" },
            new() { Code = "BA", Name = "Bosnia và Herzegovina" },
            new() { Code = "BW", Name = "Botswana" },
            new() { Code = "BR", Name = "Brazil" },
            new() { Code = "BN", Name = "Brunei" },
            new() { Code = "BG", Name = "Bulgaria" },
            new() { Code = "BF", Name = "Burkina Faso" },
            new() { Code = "BI", Name = "Burundi" },
            new() { Code = "KH", Name = "Campuchia" },
            new() { Code = "CM", Name = "Cameroon" },
            new() { Code = "CA", Name = "Canada" },
            new() { Code = "CV", Name = "Cape Verde" },
            new() { Code = "CF", Name = "Cộng hòa Trung Phi" },
            new() { Code = "TD", Name = "Chad" },
            new() { Code = "CL", Name = "Chile" },
            new() { Code = "CN", Name = "Trung Quốc" },
            new() { Code = "CO", Name = "Colombia" },
            new() { Code = "KM", Name = "Comoros" },
            new() { Code = "CG", Name = "Congo" },
            new() { Code = "CD", Name = "Cộng hòa Dân chủ Congo" },
            new() { Code = "CR", Name = "Costa Rica" },
            new() { Code = "HR", Name = "Croatia" },
            new() { Code = "CU", Name = "Cuba" },
            new() { Code = "CY", Name = "Síp" },
            new() { Code = "CZ", Name = "Séc" },
            new() { Code = "DK", Name = "Đan Mạch" },
            new() { Code = "DJ", Name = "Djibouti" },
            new() { Code = "DM", Name = "Dominica" },
            new() { Code = "DO", Name = "Cộng hòa Dominica" },
            new() { Code = "EC", Name = "Ecuador" },
            new() { Code = "EG", Name = "Ai Cập" },
            new() { Code = "SV", Name = "El Salvador" },
            new() { Code = "GQ", Name = "Guinea Xích Đạo" },
            new() { Code = "ER", Name = "Eritrea" },
            new() { Code = "EE", Name = "Estonia" },
            new() { Code = "SZ", Name = "Eswatini" },
            new() { Code = "ET", Name = "Ethiopia" },
            new() { Code = "FJ", Name = "Fiji" },
            new() { Code = "FI", Name = "Phần Lan" },
            new() { Code = "FR", Name = "Pháp" },
            new() { Code = "GA", Name = "Gabon" },
            new() { Code = "GM", Name = "Gambia" },
            new() { Code = "GE", Name = "Georgia" },
            new() { Code = "DE", Name = "Đức" },
            new() { Code = "GH", Name = "Ghana" },
            new() { Code = "GR", Name = "Hy Lạp" },
            new() { Code = "GD", Name = "Grenada" },
            new() { Code = "GT", Name = "Guatemala" },
            new() { Code = "GN", Name = "Guinea" },
            new() { Code = "GW", Name = "Guinea-Bissau" },
            new() { Code = "GY", Name = "Guyana" },
            new() { Code = "HT", Name = "Haiti" },
            new() { Code = "HN", Name = "Honduras" },
            new() { Code = "HU", Name = "Hungary" },
            new() { Code = "IS", Name = "Iceland" },
            new() { Code = "IN", Name = "Ấn Độ" },
            new() { Code = "ID", Name = "Indonesia" },
            new() { Code = "IR", Name = "Iran" },
            new() { Code = "IQ", Name = "Iraq" },
            new() { Code = "IE", Name = "Ai-len" },
            new() { Code = "IL", Name = "Israel" },
            new() { Code = "IT", Name = "Ý" },
            new() { Code = "JM", Name = "Jamaica" },
            new() { Code = "JP", Name = "Nhật Bản" },
            new() { Code = "JO", Name = "Jordan" },
            new() { Code = "KZ", Name = "Kazakhstan" },
            new() { Code = "KE", Name = "Kenya" },
            new() { Code = "KI", Name = "Kiribati" },
            new() { Code = "KP", Name = "Triều Tiên" },
            new() { Code = "KR", Name = "Hàn Quốc" },
            new() { Code = "KW", Name = "Kuwait" },
            new() { Code = "KG", Name = "Kyrgyzstan" },
            new() { Code = "LA", Name = "Lào" },
            new() { Code = "LV", Name = "Latvia" },
            new() { Code = "LB", Name = "Liban" },
            new() { Code = "LS", Name = "Lesotho" },
            new() { Code = "LR", Name = "Liberia" },
            new() { Code = "LY", Name = "Libya" },
            new() { Code = "LI", Name = "Liechtenstein" },
            new() { Code = "LT", Name = "Lithuania" },
            new() { Code = "LU", Name = "Luxembourg" },
            new() { Code = "MG", Name = "Madagascar" },
            new() { Code = "MW", Name = "Malawi" },
            new() { Code = "MY", Name = "Malaysia" },
            new() { Code = "MV", Name = "Maldives" },
            new() { Code = "ML", Name = "Mali" },
            new() { Code = "MT", Name = "Malta" },
            new() { Code = "MH", Name = "Marshall Islands" },
            new() { Code = "MR", Name = "Mauritania" },
            new() { Code = "MU", Name = "Mauritius" },
            new() { Code = "MX", Name = "Mexico" },
            new() { Code = "FM", Name = "Micronesia" },
            new() { Code = "MD", Name = "Moldova" },
            new() { Code = "MC", Name = "Monaco" },
            new() { Code = "MN", Name = "Mông Cổ" },
            new() { Code = "ME", Name = "Montenegro" },
            new() { Code = "MA", Name = "Ma-rốc" },
            new() { Code = "MZ", Name = "Mozambique" },
            new() { Code = "MM", Name = "Myanmar" },
            new() { Code = "NA", Name = "Namibia" },
            new() { Code = "NR", Name = "Nauru" },
            new() { Code = "NP", Name = "Nepal" },
            new() { Code = "NL", Name = "Hà Lan" },
            new() { Code = "NZ", Name = "New Zealand" },
            new() { Code = "NI", Name = "Nicaragua" },
            new() { Code = "NE", Name = "Niger" },
            new() { Code = "NG", Name = "Nigeria" },
            new() { Code = "MK", Name = "Bắc Macedonia" },
            new() { Code = "NO", Name = "Na Uy" },
            new() { Code = "OM", Name = "Oman" },
            new() { Code = "PK", Name = "Pakistan" },
            new() { Code = "PW", Name = "Palau" },
            new() { Code = "PA", Name = "Panama" },
            new() { Code = "PG", Name = "Papua New Guinea" },
            new() { Code = "PY", Name = "Paraguay" },
            new() { Code = "PE", Name = "Peru" },
            new() { Code = "PH", Name = "Philippines" },
            new() { Code = "PL", Name = "Ba Lan" },
            new() { Code = "PT", Name = "Bồ Đào Nha" },
            new() { Code = "QA", Name = "Qatar" },
            new() { Code = "RO", Name = "Romania" },
            new() { Code = "RU", Name = "Nga" },
            new() { Code = "RW", Name = "Rwanda" },
            new() { Code = "KN", Name = "Saint Kitts và Nevis" },
            new() { Code = "LC", Name = "Saint Lucia" },
            new() { Code = "VC", Name = "Saint Vincent và Grenadines" },
            new() { Code = "WS", Name = "Samoa" },
            new() { Code = "SM", Name = "San Marino" },
            new() { Code = "ST", Name = "Sao Tome và Principe" },
            new() { Code = "SA", Name = "Ả Rập Xê Út" },
            new() { Code = "SN", Name = "Senegal" },
            new() { Code = "RS", Name = "Serbia" },
            new() { Code = "SC", Name = "Seychelles" },
            new() { Code = "SL", Name = "Sierra Leone" },
            new() { Code = "SG", Name = "Singapore" },
            new() { Code = "SK", Name = "Slovakia" },
            new() { Code = "SI", Name = "Slovenia" },
            new() { Code = "SB", Name = "Quần đảo Solomon" },
            new() { Code = "SO", Name = "Somalia" },
            new() { Code = "ZA", Name = "Nam Phi" },
            new() { Code = "SS", Name = "Nam Sudan" },
            new() { Code = "ES", Name = "Tây Ban Nha" },
            new() { Code = "LK", Name = "Sri Lanka" },
            new() { Code = "SD", Name = "Sudan" },
            new() { Code = "SR", Name = "Suriname" },
            new() { Code = "SE", Name = "Thụy Điển" },
            new() { Code = "CH", Name = "Thụy Sĩ" },
            new() { Code = "SY", Name = "Syria" },
            new() { Code = "TW", Name = "Đài Loan" },
            new() { Code = "TJ", Name = "Tajikistan" },
            new() { Code = "TZ", Name = "Tanzania" },
            new() { Code = "TH", Name = "Thái Lan" },
            new() { Code = "TL", Name = "Đông Timor" },
            new() { Code = "TG", Name = "Togo" },
            new() { Code = "TO", Name = "Tonga" },
            new() { Code = "TT", Name = "Trinidad và Tobago" },
            new() { Code = "TN", Name = "Tunisia" },
            new() { Code = "TR", Name = "Thổ Nhĩ Kỳ" },
            new() { Code = "TM", Name = "Turkmenistan" },
            new() { Code = "TV", Name = "Tuvalu" },
            new() { Code = "UG", Name = "Uganda" },
            new() { Code = "UA", Name = "Ukraina" },
            new() { Code = "AE", Name = "Các Tiểu vương quốc Ả Rập Thống nhất" },
            new() { Code = "GB", Name = "Vương quốc Anh" },
            new() { Code = "US", Name = "Hoa Kỳ" },
            new() { Code = "UY", Name = "Uruguay" },
            new() { Code = "UZ", Name = "Uzbekistan" },
            new() { Code = "VU", Name = "Vanuatu" },
            new() { Code = "VA", Name = "Vatican" },
            new() { Code = "VE", Name = "Venezuela" },
            new() { Code = "VN", Name = "Việt Nam" },
            new() { Code = "YE", Name = "Yemen" },
            new() { Code = "ZM", Name = "Zambia" },
            new() { Code = "ZW", Name = "Zimbabwe" }
        };

        public static new List<EducationLevel> educationLevels = new List<EducationLevel>
        {
            new EducationLevel { Code = "kindergarten", Name = "Mầm non" },
            new EducationLevel { Code = "primary", Name = "Tiểu học" },
            new EducationLevel { Code = "lower_secondary", Name = "THCS (lớp 6 - lớp 9)" },
            new EducationLevel { Code = "upper_secondary", Name = "THPT (lớp 10 - lớp 12)" },
            new EducationLevel { Code = "vocational_elementary", Name = "Sơ cấp nghề" },
            new EducationLevel { Code = "intermediate", Name = "Trung cấp" },
            new EducationLevel { Code = "college", Name = "Cao đẳng" },
            new EducationLevel { Code = "university", Name = "Đại học" },
            new EducationLevel { Code = "postgraduate_master", Name = "Sau đại học - thạc sĩ" },
            new EducationLevel { Code = "postgraduate_doctor", Name = "Sau đại học - tiến sĩ" }
        };
    }
}